#!/bin/bash
output=`cat /dev/stdin | sed "s/'/\"/g"`
repo=`echo $output | jq '.repo' | sed 's/"//g'`
giturl=`echo $output | jq '.giturl'| sed 's/"//g'`
refspec=`echo $output | jq '.branch'| sed 's/"//g'`
commit=`echo $output | jq '.commit'| sed 's/"//g'`
JENKINS_SERVER=192.168.99.100:8080

#echo "$repo $giturl $refspec $commit"

cd /tmp
rm -rf $commit
git clone $giturl $commit
cd $commit
git checkout $commit
export PATH=$PATH:/home/vagrant/git/jenkins-job-builder/venvjenkins/bin
if [ -f ci.yml ]; then
 jenkins-jobs --conf /home/vagrant/git/jenkins-job-builder/etc/jenkins_jobs.ini  update ci.yml
 rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi
 job_name=`jenkins-jobs --conf /home/vagrant/git/jenkins-job-builder/etc/jenkins_jobs.ini test /tmp/${commit}/ci.yml 2>&1 | tee | grep -i "job name" | awk '{ if(match($0, /Job name: (.*)/ , m)) print m[1] }' | sed 's/ //g'`
 echo "$job_name"
  #java -jar /home/vagrant/git/jenkins-job-builder/jenkins-cli.jar -s http://${JENKINS_SERVER}/ -i ~/.ssh/stanley_rsa build $job_name 
  #cd /home/vagrant/git/st2
  #source venv/bin/activate
  #st2 action execute jenkins.build_job project=$job_name
 exit $?
else 
   echo "ci.yml doesnt exist in repo $giturl $refspec $commit"
   exit -2
fi
