#!/bin/bash
set -x
#output=`cat /dev/stdin | sed "s/'/\"/g"`
#repo=`echo $output | jq '.repo' | sed 's/"//g'`
#slug=`echo $output | jq '.slug'| sed 's/"//g'`
#refspec=`echo $output | jq '.branch'| sed 's/"//g'`
#commit=`echo $output | jq '.commit'| sed 's/"//g'`
repo=$1
slug=$2
commit=$3
base_url="https://github.com/"
JENKINS_SERVER=192.168.99.100:8080
giturl="$base_url/$repo/$slug"
jenkins_conf=/var/jenkins_home/conf/jenkins_jobs.ini
echo "$repo $giturl $refspec $commit"

cd /tmp
rm -rf $commit
git clone $giturl $commit
cd $commit
git checkout $commit
. /var/jenkins_home/venv/bin/activate
#export PATH=$PATH:/var/jenkins_home/venv/bin
if [ -f ci.yml ]; then
 jenkins-jobs --conf $jenkins_conf  update ci.yml
 rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi
 job_name=`jenkins-jobs --conf $jenkins_conf test /tmp/${commit}/ci.yml 2>&1 | tee | grep -i "job name" | awk '{ if(match($0, /Job name: (.*)/ , m)) print m[1] }' | sed 's/ //g'`
 echo "$job_name"
  #java -jar /home/vagrant/git/jenkins-job-builder/jenkins-cli.jar -s http://${JENKINS_SERVER}/ -i ~/.ssh/stanley_rsa build $job_name 
  #cd /home/vagrant/git/st2
  #source venv/bin/activate
  #st2 action execute jenkins.build_job project=$job_name
 exit $?
else 
   echo "ci.yml doesnt exist in repo $giturl $refspec $commit"
   exit -2
fi
